services:
  postgres:
    image: postgres:17.2
    container_name: warehouse-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: warehouse_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d warehouse_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: warehouse-backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/warehouse_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      JWT_SECRET: yourVeryLongSecretKeyForDiplomaProject12345678901234567890123456789012345678901234567890
      JWT_EXPIRATION: 86400000
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: warehouse-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres-data:
