spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/warehouse_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

jwt.secret=${JWT_SECRET:yourVeryLongSecretKeyForDiplomaProject12345678901234567890123456789012345678901234567890}
jwt.expiration=${JWT_EXPIRATION:86400000}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
